In umake-share, auto execute install.sh if not yet.
git-svn-id: file:///mnt/i/1027-HOME-svnreps/nlscan-svnreps/makingsys/GnumakeUniproc/trunk@1196 429491bc-2e6e-d343-9161-6a1f6e34ed84

diff --git a/GMU-main/umake_cmd/bashcmd/umake-share b/GMU-main/umake_cmd/bashcmd/umake-share
--- a/GMU-main/umake_cmd/bashcmd/umake-share
+++ b/GMU-main/umake_cmd/bashcmd/umake-share
@@ -9,6 +9,16 @@ export gmu_DIR_ROOT=${tmpbatdir%/GMU-main/umake_cmd/bashcmd}
 
 PATH=$tmpbatdir:$PATH
 
+# If there is sign that GMU is not "installed", do the install automatically.
+if [ ! -f $tmpbatdir/gmuExtractVarDefines ]; then
+	echo "First time run umake? GMU is now installing for you... "
+	if ! $gmu_DIR_ROOT/install.sh ;then
+		echo "Sorry, GMU install fails. umake cannot run."
+		exit 1
+	fi
+fi
+
+
 source $gmu_DIR_ROOT/_gmuenv.sc
 
 
